"""Render the committed run results as a table. Runs no parser itself.

    python3 conformance/maintaining/report.py [--check]

Reads every conformance/reports/*.json — the output of `conformance/run.sh` —
and writes conformance/report.html, which the README links to. An implementation
appears because its result file is committed; leaving a file out is how a
column stays off the published page.

--check writes nothing and exits non-zero if any output is out of date.
"""

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import page
import suite

ROOT, SUITE, REPORTS = suite.ROOT, suite.SUITE, suite.REPORTS
PAGE = ROOT / "conformance" / "report.html"
COVERAGE = ROOT / "conformance" / "maintaining" / "COVERAGE.md"
SECTIONS_MD = ROOT / "conformance" / "maintaining" / "SECTIONS.md"
# sections whose rules live in typed accessors the oracle protocol never calls;
# their cases pin only that the value survives the parse
NOT_MEASURED = {"units-format", "duration-format", "period-format", "size-in-bytes-format"}


def load_runs():
    """One entry per implementation, carrying its verdicts in both modes."""
    runs = {}
    for f in sorted(REPORTS.glob("*.json")):
        r = json.loads(f.read_text())
        impl = runs.setdefault(r["implementation"], {"version": r["version"], "modes": {}, "outputs": {}})
        impl["modes"][r["mode"]] = r["cases"]
        impl.setdefault("digests", set()).add(r.get("suite_digest", "none"))
        impl["outputs"].update(r.get("outputs", {}))
    for impl in runs.values():
        impl["modes"].setdefault("java", impl["modes"].get("spec", {}))
        impl["modes"].setdefault("spec", impl["modes"].get("java", {}))
    return runs


def main(argv):
    check = "--check" in argv

    cases, metas, orphans = suite.cases()
    if not cases:
        sys.exit("no cases found")
    runs = load_runs()
    if not runs:
        sys.exit("no results in {} — run conformance/run.sh first".format(REPORTS))
    impls = list(runs)

    # a result file scored against a different set of cases is not a result about
    # this suite; saying so is cheaper than quietly publishing last week's numbers
    now = suite.digest()
    behind = [i for i in impls if runs[i].get("digests", {"none"}) != {now}]
    if behind:
        print("results predate the current cases, re-run conformance/run.sh for:\n  "
              + "\n  ".join(behind))
        if check:
            return 1

    rel = [suite.key_of(c) for c in cases]
    verdict = lambda impl, key, mode: runs[impl]["modes"][mode].get(key, "open")

    sections, split = {}, []
    for case, meta, key in zip(cases, metas, rel):
        row = {"key": key, "name": suite.name_of(case), "why": meta.get("why", ""), "kind": meta.get("java", ""),
               "review": meta.get("review", ""),
               "v": {i: {m: verdict(i, key, m) for m in ("spec", "java")} for i in impls}}
        sections.setdefault(suite.section_of(case), []).append(row)
        if meta.get("java"):
            split.append({
                "input": suite.encode(case.open(newline="").read()) if not suite.is_dir_case(case)
                         else "{}/ (directory)".format(suite.name_of(case)),
                "kind": meta["java"],
                "spec_side": "rejects" if "error" in meta else "`" + json.dumps(meta["expect"]) + "`",
                "got": {i: runs[i]["outputs"].get(key, "—") for i in impls},
            })

    all_rows = [r for rows in sections.values() for r in rows]
    # coverage against the rule inventory: an item with no case is a
    # rule this suite does not check, whatever its pass rate says
    items = suite.spec_items()
    tagged = {}
    for c, m in zip(cases, metas):
        if m.get("item"):
            tagged.setdefault(m["item"], []).append(suite.key_of(c))
    known = {i for i in tagged if i in items}
    coverage = "\n".join(
        ["# Rule coverage", "",
         "{} of {} items in `spec-items.md` have at least one case ({:.0f}%).".format(
             len(known), len(items), 100 * len(known) / len(items)),
         "", "Generated by `report.py`. An item listed here is a rule the suite does not",
         "check — not a rule an implementation fails.", "", "## Unchecked", ""]
        + ["- **{}** {}".format(i, t) for i, t in items.items() if i not in known]
        + ["", "## Cases pointing at an item that is not in the inventory", ""]
        + (["- `{}` → `{}`".format(f, i) for i in tagged if i not in items for f in tagged[i]] or ["none"])
        + [""])

    # SECTIONS.md keeps its prose by hand; only the state column is derived, so
    # it cannot drift from the disk the way it did before
    import re
    counts = {name: len(rows) for name, rows in sections.items()}
    sec_lines, seen = [], set()
    for line in SECTIONS_MD.read_text().splitlines():
        m = re.match(r"^(\| \d+ \| .*? \| `)([a-z0-9-]+)(` \| ).*\|$", line)
        if m:
            d = m.group(2); seen.add(d)
            n = counts.get(d, 0)
            if d in NOT_MEASURED and n:
                state = "⚠ {} cases, not measured".format(n)
            elif n:
                state = "✅ {} cases".format(n)
            else:
                state = "— no cases yet"
            line = "{}{}{}{} |".format(m.group(1), d, m.group(3), state)
        sec_lines.append(line)
    unlisted = sorted(set(counts) - seen)
    if unlisted:
        print("directories with no row in SECTIONS.md (add one by hand):\n  " + "\n  ".join(unlisted))
    sections_md = "\n".join(sec_lines) + "\n"

    html_sections = [{"name": n, "rows": sections[n]} for n in sorted(sections)]
    lede = ("Every row is one sentence of the HOCON specification, turned into a config file and an "
            "expected value. Score against the specification and you get conformance; score against "
            "typesafe/config and you get compatibility with the implementation the JVM world runs.")
    html = page.build(impls, html_sections, split, lede,
                      {i: runs[i]["version"] for i in impls}, now)

    stale = [str(p.relative_to(ROOT)) for p, content in
             ((PAGE, html), (COVERAGE, coverage), (SECTIONS_MD, sections_md))
             if not p.exists() or p.read_text() != content]
    if orphans:
        print("no sidecar, skipped:\n  " + "\n  ".join(str(o.relative_to(ROOT)) for o in orphans))
    if check:
        if stale:
            print("out of date:\n  " + "\n  ".join(stale))
            return 1
        print("up to date")
        return 0
    PAGE.write_text(html)
    COVERAGE.write_text(coverage)
    SECTIONS_MD.write_text(sections_md)
    print("{} cases, {} sections, {} implementations".format(len(all_rows), len(sections), len(impls)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
