"""Render the committed run results as a table. Runs no parser itself.

    python3 conformance/maintaining/report.py [--check]

Reads every conformance/reports/*.json — the output of `conformance/run.sh` —
and writes both the README table and conformance/report.html. An implementation
appears because its result file is committed; leaving a file out is how a
column stays off the published page.

--check writes nothing and exits non-zero if either output is out of date.
"""

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import page
import suite

ROOT, SUITE, REPORTS = suite.ROOT, suite.SUITE, suite.REPORTS
README = ROOT / "README.md"
PAGE = ROOT / "conformance" / "report.html"
START, END = "<!-- conformance:start -->", "<!-- conformance:end -->"
MARK = {"pass": "✅", "fail": "❌", "open": "⚠"}


def load_runs():
    """One entry per implementation, carrying its verdicts in both modes."""
    runs = {}
    for f in sorted(REPORTS.glob("*.json")):
        r = json.loads(f.read_text())
        impl = runs.setdefault(r["implementation"], {"version": r["version"], "modes": {}, "outputs": {}})
        impl["modes"][r["mode"]] = r["cases"]
        impl["outputs"].update(r.get("outputs", {}))
    for impl in runs.values():
        impl["modes"].setdefault("java", impl["modes"].get("spec", {}))
        impl["modes"].setdefault("spec", impl["modes"].get("java", {}))
    return runs


def main(argv):
    check = "--check" in argv

    cases, metas, orphans = suite.cases()
    if not cases:
        sys.exit("no cases found")
    runs = load_runs()
    if not runs:
        sys.exit("no results in {} — run conformance/run.sh first".format(REPORTS))
    impls = list(runs)

    rel = [str(c.relative_to(SUITE)) for c in cases]
    verdict = lambda impl, key, mode: runs[impl]["modes"][mode].get(key, "open")

    sections, split = {}, []
    for case, meta, key in zip(cases, metas, rel):
        row = {"name": case.stem, "why": meta.get("why", ""), "kind": meta.get("java", ""),
               "review": meta.get("review", ""),
               "v": {i: {m: verdict(i, key, m) for m in ("spec", "java")} for i in impls}}
        sections.setdefault(case.parent.name, []).append(row)
        if meta.get("java"):
            split.append({
                "input": suite.encode(case.read_text()),
                "kind": meta["java"],
                "spec_side": "rejects" if "error" in meta else "`" + json.dumps(meta["expect"]) + "`",
                "got": {i: runs[i]["outputs"].get(key, "—") for i in impls},
            })

    # --- markdown, for the README ---
    def tally(rows, impl, mode):
        return sum(r["v"][impl][mode] == "pass" for r in rows), len(rows)

    pct = lambda p, n: "{:.0f}%".format(100 * p / n) if n else "—"
    head = " | ".join(impls)
    out = [START, "", "<!-- generated by conformance/maintaining/report.py — do not edit by hand -->", ""]

    if split:
        out += ["<details open>",
                "<summary><b>Where HOCON and typesafe/config part ways</b> — {} rows</summary>".format(len(split)),
                "", "| input | the spec requires | " + head + " |", "|---|---|" + "---|" * len(impls)]
        for r in split:
            out.append("| `{}` | {} | {} |".format(
                r["input"].replace("|", "\\|"), r["spec_side"],
                " | ".join("`{}`".format(r["got"][i].replace("|", "\\|")) for i in impls)))
        out += ["", "Each column is what that implementation actually returns.", "", "</details>", ""]

    all_rows = [r for rows in sections.values() for r in rows]
    for name in sorted(sections):
        rows = sections[name]
        head_line = " · ".join("{} {}/{}".format(i, *tally(rows, i, "spec")) for i in impls)
        out += ["<details>",
                "<summary><b>{}</b> — {} cases · {}</summary>".format(name, len(rows), head_line),
                "", "| case | " + head + " | rule |", "|---|" + "---|" * (len(impls) + 1)]
        for r in rows:
            note = r["why"] + (" _(java: {})_".format(r["kind"]) if r["kind"] else "")
            note += " **⚠ {}**".format(r["review"]) if r["review"] else ""
            out.append("| `{}` | {} | {} |".format(
                r["name"], " | ".join(MARK[r["v"][i]["spec"]] for i in impls), note))
        out += ["", "</details>", ""]

    out += ["| {} cases | ".format(len(all_rows))
            + " | ".join("{}<br><sub>{}</sub>".format(i, runs[i]["version"]) for i in impls) + " |",
            "|---|" + "---|" * len(impls)]
    for mode, label in (("spec", "**spec mode** — what HOCON requires"),
                        ("java", "**java mode** — what typesafe/config does")):
        cells = []
        for i in impls:
            p, n = tally(all_rows, i, mode)
            cells.append("{}{}{} ({}/{})".format("**" if mode == "spec" else "",
                                                 pct(p, n), "**" if mode == "spec" else "", p, n))
        out += ["| {} | {} |".format(label, " | ".join(cells))]
    open_rows = sum(1 for r in all_rows if r["review"])
    out += ["", "Cells show **spec mode**. The two differ only on the {} rows marked `java:`. "
            "{} rows are open questions (⚠) rather than results. Columns appear here because their "
            "result file is committed under `conformance/reports/`.".format(len(split), open_rows),
            "", END]
    block = "\n".join(out)

    text = README.read_text()
    new = (text[:text.index(START)] + block + text[text.index(END) + len(END):]
           if START in text and END in text
           else text.rstrip() + "\n\n## Conformance\n\n" + block + "\n")

    html_sections = [{"name": n, "rows": sections[n]} for n in sorted(sections)]
    lede = ("Every row is one sentence of the HOCON specification, turned into a config file and an "
            "expected value. Score against the specification and you get conformance; score against "
            "typesafe/config and you get compatibility with the implementation the JVM world runs.")
    html = page.build(impls, html_sections, split, lede, {i: runs[i]["version"] for i in impls})

    stale = [str(p.relative_to(ROOT)) for p, content in ((README, new), (PAGE, html))
             if not p.exists() or p.read_text() != content]
    if orphans:
        print("no sidecar, skipped:\n  " + "\n  ".join(str(o.relative_to(ROOT)) for o in orphans))
    if check:
        if stale:
            print("out of date:\n  " + "\n  ".join(stale))
            return 1
        print("up to date")
        return 0
    README.write_text(new)
    PAGE.write_text(html)
    print("{} cases, {} sections, {} implementations".format(len(all_rows), len(sections), len(impls)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
