"""Run the conformance suite against every oracle and write the README table.

    python3 tools/conformance/report.py [--check]

Each implementation gets a column, each case a row, grouped into one <details>
per spec section. The table is written into README.md between the
conformance:start / conformance:end markers. --check writes nothing and exits
non-zero if the committed table is out of date.
"""

import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SUITE = ROOT / "conformance"
README = ROOT / "README.md"
START, END = "<!-- conformance:start -->", "<!-- conformance:end -->"

# label -> command. A missing binary drops the column rather than failing the run.
IMPLS = [
    ("Java", [ROOT / "tools" / "oracle" / "hocon-java"]),
    ("pyhocon", [ROOT / "tools" / "oracle" / "hocon-py"]),
    ("Rust", [ROOT / "tools" / "oracle" / "rust-oracle" / "target" / "release" / "rust-oracle"]),
]


def encode(src):
    # the wrappers drop blank input lines, so an empty document has to travel as
    # whitespace — same parse, and it keeps one line in == one line out
    # ponytail: only empty-vs-whitespace is affected; fix the wrappers if a case
    # ever needs to distinguish them
    if not src.strip():
        src = " " + src.lstrip("\n")
    return src.replace("\\", "\\\\").replace("\t", "\\t").replace('"', '\\"').replace("\n", "\\n")


def ask(cmd, lines):
    out = subprocess.run([str(c) for c in cmd], input="\n".join(lines) + "\n",
                         capture_output=True, text=True).stdout.splitlines()
    # a crashed or short-circuiting oracle must not silently shift every answer
    return out if len(out) == len(lines) else ["ERROR OracleFailed: short output"] * len(lines)


def verdict(answer, meta):
    if "error" in meta:
        return "pass" if answer.startswith("ERROR") else "fail"
    if answer.startswith("ERROR"):
        return "fail"
    try:
        return "pass" if json.loads(answer) == meta["expect"] else "fail"
    except json.JSONDecodeError:
        return "fail"


MARK = {"pass": "✅", "fail": "❌", "todo": "·", "review": "⚠"}


def as_java_sees_it(meta):
    """Java is scored against what the spec says, except on a declared divergence,
    where it is scored against its own recorded behaviour — otherwise the column
    would report the gap between spec and implementation as a Java bug."""
    if "java_expect" in meta:
        return {"expect": meta["java_expect"]}
    if "java_error" in meta:
        return {"error": meta["java_error"]}
    return meta


def main(argv):
    check = "--check" in argv

    cases = sorted(SUITE.rglob("*.conf"))
    if not cases:
        sys.exit("no cases found")
    orphans = [c for c in cases if not c.with_suffix(".json").exists()]
    if orphans:
        print("no sidecar, skipped:\n  " + "\n  ".join(str(o.relative_to(ROOT)) for o in orphans))
        cases = [c for c in cases if c not in set(orphans)]
    metas = [json.loads(c.with_suffix(".json").read_text()) for c in cases]
    lines = [("resolve:" if m.get("resolve") else "") + encode(c.read_text())
             for c, m in zip(cases, metas)]

    impls = [(label, cmd) for label, cmd in IMPLS if pathlib.Path(cmd[0]).exists()]
    results = {label: ask(cmd, lines) for label, cmd in impls}

    sections = {}
    for case, meta, i in zip(cases, metas, range(len(cases))):
        row = {"name": case.stem, "why": meta.get("why", ""), "java_note": meta.get("java"),
               "review": meta.get("review"), "cells": {}}
        for label, _ in impls:
            if "review" in meta:
                row["cells"][label] = "review"
            elif "expect" not in meta and "error" not in meta:
                row["cells"][label] = "todo"
            else:
                row["cells"][label] = verdict(results[label][i],
                                              as_java_sees_it(meta) if label == "Java" else meta)
        sections.setdefault(case.parent.name, []).append(row)

    html = [START, "", "<!-- generated by tools/conformance/report.py — do not edit by hand -->", ""]
    totals = {label: [0, 0] for label, _ in impls}
    for name in sorted(sections):
        rows = sections[name]
        done = {label: sum(1 for r in rows if r["cells"][label] == "pass") for label, _ in impls}
        n = len(rows)
        head = " · ".join("{} {}/{}".format(label, done[label], n) for label, _ in impls)
        html += ["<details>", "<summary><b>{}</b> — {} cases · {}</summary>".format(name, n, head), "",
                 "| case | " + " | ".join(label for label, _ in impls) + " | rule |",
                 "|---|" + "---|" * (len(impls) + 1)]
        for r in rows:
            note = r["why"] + ("" if not r["java_note"] else " _(java: {})_".format(r["java_note"]))
            if r["review"]:
                note += " **⚠ {}**".format(r["review"])
            html.append("| `{}` | {} | {} |".format(
                r["name"], " | ".join(MARK[r["cells"][label]] for label, _ in impls), note))
            for label, _ in impls:
                totals[label][1] += 1
                totals[label][0] += r["cells"][label] == "pass"
        html += ["", "</details>", ""]

    pct = lambda p, n: "{:.0f}%".format(100 * p / n) if n else "—"
    html += ["| total | " + " | ".join(label for label, _ in impls) + " |",
             "|---|" + "---|" * len(impls),
             "| **{} cases** | ".format(sum(totals[impls[0][0]][1:]) if impls else 0)
             + " | ".join("**{}** ({}/{})".format(pct(*totals[label]), *totals[label])
                          for label, _ in impls) + " |",
             "", "{} of {} rows are open questions (⚠) rather than results.".format(
                 sum(1 for rows in sections.values() for r in rows if r["review"]), len(cases)),
             "", END]
    block = "\n".join(html)

    text = README.read_text()
    if START in text and END in text:
        new = text[:text.index(START)] + block + text[text.index(END) + len(END):]
    else:
        new = text.rstrip() + "\n\n## Conformance\n\n" + block + "\n"

    if new == text:
        print("table up to date")
        return 0
    if check:
        print("README conformance table is out of date")
        return 1
    README.write_text(new)
    print("{} cases, {} sections, {} implementations".format(len(cases), len(sections), len(impls)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
