"""Run the conformance suite against every oracle and write the README table.

    python3 tools/conformance/report.py [--check]

Each implementation gets a column, each case a row, grouped into one <details>
per spec section. The table is written into README.md between the
conformance:start / conformance:end markers. --check writes nothing and exits
non-zero if the committed table is out of date.
"""

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import page
import suite

ROOT, SUITE = suite.ROOT, suite.SUITE
README = ROOT / "README.md"
START, END = "<!-- conformance:start -->", "<!-- conformance:end -->"

# label -> command. A missing binary drops the column rather than failing the run.
IMPLS = [
    ("Java", [ROOT / "tools" / "oracle" / "hocon-java"]),
    ("pyhocon", [ROOT / "tools" / "oracle" / "hocon-py"]),
    ("Rust", [ROOT / "tools" / "oracle" / "rust-oracle" / "target" / "release" / "rust-oracle"]),
]



def shorten(answer, width=30):
    """What an implementation actually returned, short enough for a table cell.
    The point of the divergence table is the behaviour, not a verdict — a verdict
    would only restate which of the two bars the row is being scored against."""
    if answer.startswith("ERROR"):
        cls = answer[len("ERROR "):].split(":", 1)[0]
        return "rejects: " + (cls[:19] + "…" if len(cls) > 20 else cls)
    return answer if len(answer) <= width else answer[:width - 1] + "…"


def verdict(answer, meta):
    if "error" in meta:
        return "pass" if answer.startswith("ERROR") else "fail"
    if answer.startswith("ERROR"):
        return "fail"
    try:
        return "pass" if json.loads(answer) == meta["expect"] else "fail"
    except json.JSONDecodeError:
        return "fail"


MARK = {"pass": "✅", "fail": "❌", "todo": "·", "review": "⚠"}


def in_mode(meta, mode):
    """Two bars, one suite. "spec" scores against what HOCON requires; "java"
    scores against what typesafe/config does, which differs on exactly the rows
    that carry a `java` kind."""
    if mode == "java" and "java_expect" in meta:
        return {"expect": meta["java_expect"]}
    if mode == "java" and "java_error" in meta:
        return {"error": meta["java_error"]}
    return meta


def main(argv):
    check = "--check" in argv

    cases, metas, orphans = suite.cases()
    if not cases:
        sys.exit("no cases found")
    if orphans:
        print("no sidecar, skipped:\n  " + "\n  ".join(str(o.relative_to(ROOT)) for o in orphans))
    lines = [("resolve:" if m.get("resolve") else "") + suite.encode(c.read_text())
             for c, m in zip(cases, metas)]

    impls = [(label, cmd) for label, cmd in IMPLS if pathlib.Path(cmd[0]).exists()]
    results = {label: suite.ask(cmd, lines, strict=False) for label, cmd in impls}
    versions = {label: suite.version(cmd) for label, cmd in impls}

    sections = {}
    for case, meta, i in zip(cases, metas, range(len(cases))):
        row = {"name": case.stem, "why": meta.get("why", ""), "java_note": meta.get("java"),
               "review": meta.get("review"), "cells": {}, "java_mode": {}}
        for label, _ in impls:
            if "review" in meta:
                row["cells"][label] = "review"
            elif "expect" not in meta and "error" not in meta:
                row["cells"][label] = "todo"
            else:
                row["cells"][label] = verdict(results[label][i], meta)
                row["java_mode"][label] = verdict(results[label][i], in_mode(meta, "java"))
        sections.setdefault(case.parent.name, []).append(row)

    html = [START, "", "<!-- generated by tools/conformance/report.py — do not edit by hand -->", ""]

    # the rows where the two bars are not the same question — the whole point of the suite
    split = [(c, m, i) for i, (c, m) in enumerate(zip(cases, metas)) if "java" in m]
    if split:
        html += ["<details open>",
                 "<summary><b>Where HOCON and typesafe/config part ways</b> — {} rows</summary>".format(len(split)),
                 "", "| input | the spec requires | "
                 + " | ".join(label for label, _ in impls) + " |",
                 "|---|---|" + "---|" * len(impls)]
        for case, meta, i in split:
            spec_side = "rejects" if "error" in meta else "`" + json.dumps(meta["expect"]) + "`"
            java_side = "rejects" if "java_error" in meta else "`" + json.dumps(meta["java_expect"]) + "`"
            cells = [shorten(results[label][i]) for label, _ in impls]
            html.append("| `{}` | {} | {} |".format(
                suite.encode(case.read_text()).replace("|", "\\|"), spec_side,
                " | ".join("`{}`".format(c.replace("|", "\\|")) for c in cells)))
        html += ["", "Each column is what that implementation actually returns. The spec column is "
                 "the bar; Java's column is, by definition, the other bar.", "", "</details>", ""]
    totals = {label: [0, 0] for label, _ in impls}
    java_totals = {label: [0, 0] for label, _ in impls}
    for name in sorted(sections):
        rows = sections[name]
        done = {label: sum(1 for r in rows if r["cells"][label] == "pass") for label, _ in impls}
        n = len(rows)
        head = " · ".join("{} {}/{}".format(label, done[label], n) for label, _ in impls)
        html += ["<details>", "<summary><b>{}</b> — {} cases · {}</summary>".format(name, n, head), "",
                 "| case | " + " | ".join(label for label, _ in impls) + " | rule |",
                 "|---|" + "---|" * (len(impls) + 1)]
        for r in rows:
            note = r["why"] + ("" if not r["java_note"] else " _(java: {})_".format(r["java_note"]))
            if r["review"]:
                note += " **⚠ {}**".format(r["review"])
            html.append("| `{}` | {} | {} |".format(
                r["name"], " | ".join(MARK[r["cells"][label]] for label, _ in impls), note))
            for label, _ in impls:
                totals[label][1] += 1
                totals[label][0] += r["cells"][label] == "pass"
                java_totals[label][1] += 1
                java_totals[label][0] += r["java_mode"].get(label, r["cells"][label]) == "pass"
        html += ["", "</details>", ""]

    pct = lambda p, n: "{:.0f}%".format(100 * p / n) if n else "—"
    html += ["| {} cases | ".format(totals[impls[0][0]][1] if impls else 0)
             + " | ".join("{}<br><sub>{}</sub>".format(label, versions[label])
                          for label, _ in impls) + " |",
             "|---|" + "---|" * len(impls),
             "| **spec mode** — what HOCON requires | "
             + " | ".join("**{}** ({}/{})".format(pct(*totals[label]), *totals[label])
                          for label, _ in impls) + " |",
             "| **java mode** — what typesafe/config does | "
             + " | ".join("{} ({}/{})".format(pct(*java_totals[label]), *java_totals[label])
                          for label, _ in impls) + " |",
             "", "Cells above show **spec mode**. The two modes differ on the {} rows marked "
             "`java:` — the ones where HOCON and typesafe/config part ways; everywhere else they "
             "are the same question. {} rows are open questions (⚠) rather than results.".format(
                 sum(1 for rows in sections.values() for r in rows if r["java_note"]),
                 sum(1 for rows in sections.values() for r in rows if r["review"])),
             "", END]
    block = "\n".join(html)

    text = README.read_text()
    if START in text and END in text:
        new = text[:text.index(START)] + block + text[text.index(END) + len(END):]
    else:
        new = text.rstrip() + "\n\n## Conformance\n\n" + block + "\n"

    html_sections = [
        {"name": name,
         "rows": [{"name": r["name"], "why": r["why"], "kind": r["java_note"] or "",
                   "v": {label: {"spec": r["cells"][label],
                                 "java": r["java_mode"].get(label, r["cells"][label])}
                         for label, _ in impls}}
                  for r in sections[name]]}
        for name in sorted(sections)]
    split_rows = []
    for case, meta, i in split:
        split_rows.append({
            "input": suite.encode(case.read_text()),
            "spec_side": "rejects" if "error" in meta else json.dumps(meta["expect"]),
            "kind": meta["java"],
            "got": {label: shorten(results[label][i], 44) for label, _ in impls}})
    lede = ("Every row is one sentence of the HOCON specification, turned into a config file and an "
            "expected value. Score against the specification and you get conformance; score against "
            "typesafe/config and you get compatibility with the implementation the JVM world runs.")
    page_html = page.build([label for label, _ in impls], html_sections, split_rows, lede, versions)
    out_path = SUITE / "report.html"
    if not check:
        out_path.write_text(page_html)

    if new == text:
        print("table up to date")
        return 0
    if check:
        print("README conformance table is out of date")
        return 1
    README.write_text(new)
    print("{} cases, {} sections, {} implementations".format(len(cases), len(sections), len(impls)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
